[package]
name = "rtsp-mock"
version = "0.2.1"
authors = ["Talbot3 <4wunian@gmail.com>"]
edition = "2018"
description="mock rtsp stream"
documentation="https://github.com/Talbot3/PracticeRust/tree/master/packages/rtsp-mock"
homepage="https://github.com/Talbot3/PracticeRust/tree/master/packages/rtsp-mock"
repository="https://github.com/Talbot3/PracticeRust"
license="MIT"

[dependencies]
bitflags = "1.0"
libc = "0.2"
once_cell = "1.0"
glib = { version = "0.10.3" }
gstreamer = { version = "0.16.3" }
gstreamer-rtsp-server = { version = "0.16.3" }