[package]
name = "rtsp-mock"
version = "0.2.0"
authors = ["Talbot3 <4wunian@gmail.com>"]
edition = "2018"
description="mock rtsp stream"
documentation="https://github.com/Talbot3/PracticeRust/tree/master/packages/rtsp-mock"
homepage="https://github.com/Talbot3/PracticeRust/tree/master/packages/rtsp-mock"
repository="https://github.com/Talbot3/PracticeRust"
license="MIT"

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

[dependencies]
glib = { version = "0.9.0" }
gstreamer = { version = "0.15.0" }
gstreamer-rtsp-server = { version = "0.15.0" }